language: objective-c
osx_image: xcode9.2
sudo: true

cache:
  directories:
    - Carthage
    - Inspector/node_modules

script: ./Scripts/build.sh

env:
  global:
    - TARGET=lib
    - SDK=sim
    - PLATFORM_VERSION=11.2

matrix:
  include:
    # Analyze
    - env:
        - ACTION=analyze
    - env:
        - ACTION=analyze TARGET=runner

    # Unit tests
    - env:
        - ACTION=unit_test DEST=iphone
    - env:
        - ACTION=unit_test DEST=ipad

    # Integration tests iPhone
    - env:
        - ACTION=int_test_1 DEST=iphone
    - env:
        - ACTION=int_test_2 DEST=iphone
    - env:
        - ACTION=int_test_3 DEST=iphone

    # Integration tests iPad
    - env:
        - ACTION=int_test_1 DEST=ipad
    - env:
        - ACTION=int_test_2 DEST=ipad
    - env:
        - ACTION=int_test_3 DEST=ipad

    # smoke test on xcode 8.3
    - osx_image: xcode8.3
      env:
        - ACTION=analyze PLATFORM_VERSION=10.3
    - osx_image: xcode8.3
      env:
        - ACTION=analyze TARGET=runner SDK=device PLATFORM_VERSION=10.3
